// ECharts chart templates — a curated, non-coder-friendly gallery.
// Each `defaultConfig` is a complete EChartsConfig so the editor can apply it
// directly via `onChange(deepClone(defaultConfig))`.

import type { EChartsConfig } from '@/types/chart'

export interface EChartsTemplate {
  id: string
  name: string
  description: string
  category: string
  /** Underlying echarts `type` (bar | line | pie | scatter | radar | funnel | gauge | heatmap |
   *  candlestick | boxplot | graph | sankey | treemap | sunburst | parallel | themeRiver) */
  type: string
  defaultConfig: EChartsConfig
}

export const ECHARTS_TEMPLATE_CATEGORIES: { id: string; label: string }[] = [
  { id: 'bar', label: 'Bar' },
  { id: 'line', label: 'Line' },
  { id: 'pie', label: 'Pie' },
  { id: 'scatter', label: 'Scatter' },
  { id: 'radar', label: 'Radar' },
  { id: 'funnel', label: 'Funnel' },
  { id: 'gauge', label: 'Gauge' },
  { id: 'heatmap', label: 'Heatmap' },
  { id: 'candlestick', label: 'Candlestick' },
  { id: 'boxplot', label: 'Boxplot' },
  { id: 'graph', label: 'Graph' },
  { id: 'sankey', label: 'Sankey' },
  { id: 'treemap', label: 'Treemap' },
  { id: 'sunburst', label: 'Sunburst' },
  { id: 'parallel', label: 'Parallel' },
  { id: 'themeRiver', label: 'Theme River' },
]

export const ECHARTS_TEMPLATES: EChartsTemplate[] = [
  // ---------- Bar ----------
  {
    id: 'bar',
    name: 'Bar Chart',
    description: 'Classic vertical bar chart, ideal for comparing values across categories.',
    category: 'bar',
    type: 'bar',
    defaultConfig: {
      title: { text: 'Quarterly Sales Comparison', subtext: '2024 product lines (10K USD)' },
      legend: true,
      theme: 'default',
      type: 'bar',
      categories: ['Q1', 'Q2', 'Q3', 'Q4'],
      series_names: ['Product A', 'Product B', 'Product C'],
      series_data: [
        [120, 200, 150, 80],
        [90, 160, 130, 110],
        [60, 90, 75, 130],
      ],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
    },
  },
  {
    id: 'bar-horizontal',
    name: 'Horizontal Bar Chart',
    description: 'Horizontal bars — clearer when category names are long or for rankings.',
    category: 'bar',
    type: 'bar',
    defaultConfig: {
      title: { text: 'City User Activity', subtext: 'Daily active users (10K)' },
      legend: true,
      theme: 'default',
      type: 'bar',
      categories: ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Hangzhou', 'Chengdu'],
      series_names: ['DAU', 'MAU'],
      series_data: [
        [320, 410, 280, 360, 210, 180],
        [1200, 1500, 1100, 1300, 800, 700],
      ],
      stack: false,
      smooth: false,
      horizontal: true,
      showLabel: true,
      showToolbox: true,
    },
  },
  {
    id: 'bar-stack',
    name: 'Stacked Bar Chart',
    description: 'Multiple stacked series showing both totals and composition.',
    category: 'bar',
    type: 'bar',
    defaultConfig: {
      title: { text: 'Department Budget Composition', subtext: 'HR / Ops / R&D stacked (10K USD)' },
      legend: true,
      theme: 'default',
      type: 'bar',
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      series_names: ['HR', 'Ops', 'R&D'],
      series_data: [
        [40, 42, 45, 50, 48, 52],
        [25, 28, 30, 32, 35, 38],
        [55, 60, 65, 70, 72, 78],
      ],
      stack: true,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
    },
  },

  // ---------- Line ----------
  {
    id: 'line',
    name: 'Line Chart',
    description: 'Shows trends over time.',
    category: 'line',
    type: 'line',
    defaultConfig: {
      title: { text: 'Website Traffic Trend', subtext: 'Last 7 days PV / UV' },
      legend: true,
      theme: 'default',
      type: 'line',
      categories: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      series_names: ['PV', 'UV'],
      series_data: [
        [820, 932, 901, 934, 1290, 1330, 1520],
        [320, 380, 410, 430, 510, 530, 620],
      ],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
    },
  },
  {
    id: 'line-smooth',
    name: 'Smooth Line Chart',
    description: 'Curved line chart for softer trends.',
    category: 'line',
    type: 'line',
    defaultConfig: {
      title: { text: 'Temperature Changes', subtext: 'Weekly high / low (°C)' },
      legend: true,
      theme: 'default',
      type: 'line',
      categories: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      series_names: ['High', 'Low'],
      series_data: [
        [22, 25, 28, 26, 24, 21, 19],
        [12, 14, 16, 15, 13, 11, 10],
      ],
      stack: false,
      smooth: true,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
    },
  },
  {
    id: 'area',
    name: 'Area Chart',
    description: 'Line chart with shaded fill, emphasizing cumulative volume.',
    category: 'line',
    type: 'line',
    defaultConfig: {
      title: { text: 'Cumulative Sales', subtext: 'H1 monthly cumulative (10K USD)' },
      legend: true,
      theme: 'default',
      type: 'line',
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      series_names: ['Cumulative Sales'],
      series_data: [[100, 230, 380, 520, 690, 880]],
      stack: false,
      smooth: true,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
    },
  },

  // ---------- Pie ----------
  {
    id: 'pie',
    name: 'Pie Chart',
    description: 'Shows the share of each category in the total.',
    category: 'pie',
    type: 'pie',
    defaultConfig: {
      title: { text: 'Traffic Sources', subtext: 'Share of visits by channel' },
      legend: true,
      theme: 'default',
      type: 'pie',
      categories: [],
      series_names: ['Traffic'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      single_series_data: [
        { name: 'Search Engine', value: 1048 },
        { name: 'Direct', value: 735 },
        { name: 'Email', value: 580 },
        { name: 'Affiliate Ads', value: 484 },
        { name: 'Video Ads', value: 300 },
      ],
    },
  },
  {
    id: 'pie-donut',
    name: 'Donut Chart',
    description: 'Hollow pie chart — center can display a key metric.',
    category: 'pie',
    type: 'pie',
    defaultConfig: {
      title: { text: 'Device Distribution', subtext: 'Share by terminal device' },
      legend: true,
      theme: 'default',
      type: 'pie',
      categories: [],
      series_names: ['Device'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      single_series_data: [
        { name: 'iOS', value: 1280 },
        { name: 'Android', value: 1890 },
        { name: 'Web', value: 760 },
        { name: 'Mini Program', value: 420 },
      ],
    },
  },

  // ---------- Scatter ----------
  {
    id: 'scatter',
    name: 'Scatter Plot',
    description: 'Shows the distribution of two variables.',
    category: 'scatter',
    type: 'scatter',
    defaultConfig: {
      title: { text: 'Height vs Weight', subtext: 'Sample height (cm) vs weight (kg)' },
      legend: true,
      theme: 'default',
      type: 'scatter',
      categories: [],
      series_names: ['Samples'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
      scatter_data: [
        [161, 51], [167, 59], [159, 47], [157, 53], [155, 45],
        [170, 63], [163, 56], [180, 80], [175, 72], [172, 67],
        [168, 62], [178, 75], [165, 58], [185, 88], [182, 84],
      ],
    },
  },

  // ---------- Radar ----------
  {
    id: 'radar',
    name: 'Radar Chart',
    description: 'Multi-dimensional comparison, commonly used for capability assessment.',
    category: 'radar',
    type: 'radar',
    defaultConfig: {
      title: { text: 'Capability Radar', subtext: 'Our product vs competitor' },
      legend: true,
      theme: 'default',
      type: 'radar',
      categories: [],
      series_names: ['Our Product', 'Competitor A'],
      series_data: [
        [85, 70, 90, 65, 80, 75],
        [72, 88, 65, 80, 70, 82],
      ],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      radar_indicators: [
        { name: 'Features', max: 100 },
        { name: 'Usability', max: 100 },
        { name: 'Performance', max: 100 },
        { name: 'Design', max: 100 },
        { name: 'Service', max: 100 },
        { name: 'Price', max: 100 },
      ],
    },
  },

  // ---------- Funnel ----------
  {
    id: 'funnel',
    name: 'Funnel Chart',
    description: 'Shows conversion funnels, commonly used in operations analysis.',
    category: 'funnel',
    type: 'funnel',
    defaultConfig: {
      title: { text: 'Purchase Conversion Funnel', subtext: 'From visit to repurchase' },
      legend: true,
      theme: 'default',
      type: 'funnel',
      categories: [],
      series_names: ['Conversion'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      single_series_data: [
        { name: 'Visit', value: 10000 },
        { name: 'Sign Up', value: 4500 },
        { name: 'Add to Cart', value: 2200 },
        { name: 'Place Order', value: 1300 },
        { name: 'Repurchase', value: 480 },
      ],
    },
  },

  // ---------- Gauge ----------
  {
    id: 'gauge',
    name: 'Gauge',
    description: 'Shows a single-value metric — completion rate or score.',
    category: 'gauge',
    type: 'gauge',
    defaultConfig: {
      title: { text: 'Annual Goal Completion', subtext: 'Current completion (%)' },
      legend: false,
      theme: 'default',
      type: 'gauge',
      categories: [],
      series_names: ['Completion'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      gauge_value: 68,
      gauge_max: 100,
    },
  },

  // ---------- Heatmap ----------
  {
    id: 'heatmap',
    name: 'Heatmap',
    description: 'Uses color intensity to show strength in 2D data.',
    category: 'heatmap',
    type: 'heatmap',
    defaultConfig: {
      title: { text: 'Weekly Activity Heatmap', subtext: 'Visit intensity by time slot' },
      legend: true,
      theme: 'default',
      type: 'heatmap',
      categories: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      series_names: ['0-6h', '6-12h', '12-18h', '18-24h'],
      // Heatmap reuses series_data: each inner array gives per-column values in `categories` order
      series_data: [
        [3, 4, 2, 5, 6, 8, 9],
        [12, 15, 14, 16, 18, 22, 25],
        [25, 28, 30, 32, 35, 28, 22],
        [40, 42, 38, 45, 48, 30, 26],
      ],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
    },
  },
  {
    id: 'heatmap-calendar',
    name: 'Calendar Heatmap',
    description: '24-hour x 7-day activity matrix — find your busiest time slots.',
    category: 'heatmap',
    type: 'heatmap',
    defaultConfig: {
      title: { text: 'Server Load Heatmap', subtext: 'CPU usage by day of week & hour' },
      legend: true,
      theme: 'default',
      type: 'heatmap',
      categories: [
        '0h', '1h', '2h', '3h', '4h', '5h', '6h', '7h',
        '8h', '9h', '10h', '11h', '12h', '13h', '14h', '15h',
        '16h', '17h', '18h', '19h', '20h', '21h', '22h', '23h',
      ],
      series_names: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      series_data: [
        [12, 8, 6, 5, 4, 5, 10, 28, 55, 68, 72, 70, 65, 78, 85, 80, 75, 70, 60, 50, 42, 35, 28, 20],
        [10, 7, 5, 4, 4, 6, 11, 30, 58, 70, 75, 73, 68, 80, 88, 82, 78, 72, 62, 52, 44, 36, 30, 22],
        [11, 8, 6, 5, 4, 5, 10, 29, 56, 69, 74, 71, 67, 79, 86, 81, 76, 71, 61, 51, 43, 35, 29, 21],
        [12, 8, 6, 4, 4, 5, 10, 28, 55, 68, 72, 70, 65, 78, 85, 80, 75, 70, 60, 50, 42, 35, 28, 20],
        [13, 9, 6, 5, 4, 5, 11, 27, 52, 64, 68, 66, 62, 74, 80, 76, 71, 66, 57, 47, 40, 33, 27, 19],
        [8, 6, 4, 3, 3, 3, 6, 12, 22, 30, 35, 33, 30, 36, 40, 38, 35, 32, 28, 24, 20, 17, 14, 11],
        [7, 5, 4, 3, 2, 3, 5, 10, 18, 25, 28, 27, 25, 30, 33, 32, 29, 27, 23, 20, 17, 15, 12, 10],
      ],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
    },
  },

  // ---------- Bar (extras) ----------
  {
    id: 'bar-stack-horizontal',
    name: 'Stacked Horizontal Bar',
    description: 'Stacked horizontal bars — composition across long category labels.',
    category: 'bar',
    type: 'bar',
    defaultConfig: {
      title: { text: 'Energy Consumption by Sector', subtext: 'Stacked by source (TWh)' },
      legend: true,
      theme: 'default',
      type: 'bar',
      categories: ['United States', 'China', 'India', 'Russia', 'Japan', 'Germany', 'Brazil'],
      series_names: ['Coal', 'Natural Gas', 'Nuclear', 'Renewables'],
      series_data: [
        [580, 720, 380, 220, 175, 165, 60],
        [430, 350, 90, 280, 165, 95, 75],
        [200, 60, 35, 70, 25, 25, 20],
        [180, 320, 80, 110, 95, 145, 120],
      ],
      stack: true,
      smooth: false,
      horizontal: true,
      showLabel: false,
      showToolbox: true,
    },
  },
  {
    id: 'bar-negative',
    name: 'Diverging Bar (Population Pyramid)',
    description: 'Diverging bar — male values negative, female values positive.',
    category: 'bar',
    type: 'bar',
    defaultConfig: {
      title: { text: 'Population Pyramid', subtext: 'Age distribution by gender (10K people)' },
      legend: true,
      theme: 'default',
      type: 'bar',
      categories: ['0-9', '10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80+'],
      series_names: ['Male', 'Female'],
      // Negative = male (left side), positive = female (right side)
      series_data: [
        [-580, -640, -720, -680, -560, -480, -380, -220, -90],
        [545, 615, 700, 660, 555, 480, 395, 245, 110],
      ],
      stack: false,
      smooth: false,
      horizontal: true,
      showLabel: false,
      showToolbox: true,
    },
  },
  {
    id: 'bar-race',
    name: 'Top-N Ranking Bar',
    description: 'Ranking-style bar chart — top 10 countries by GDP.',
    category: 'bar',
    type: 'bar',
    defaultConfig: {
      title: { text: 'Top 10 Countries by GDP', subtext: 'Nominal GDP 2023 (trillion USD)' },
      legend: false,
      theme: 'default',
      type: 'bar',
      categories: [
        'United States', 'China', 'Germany', 'Japan', 'India',
        'United Kingdom', 'France', 'Italy', 'Brazil', 'Canada',
      ],
      series_names: ['GDP'],
      series_data: [
        [27.36, 17.79, 4.46, 4.21, 3.55, 3.34, 3.03, 2.25, 2.13, 2.12],
      ],
      stack: false,
      smooth: false,
      horizontal: true,
      showLabel: true,
      showToolbox: true,
    },
  },
  {
    id: 'bar-waterfall',
    name: 'Cumulative Waterfall Bar',
    description: 'Cumulative-bar waterfall — running total across stages.',
    category: 'bar',
    type: 'bar',
    defaultConfig: {
      title: { text: 'Cumulative Project Spend', subtext: 'Running total by phase (10K USD)' },
      legend: false,
      theme: 'default',
      type: 'bar',
      categories: ['Planning', 'Design', 'Dev Sprint 1', 'Dev Sprint 2', 'QA', 'Launch', 'Support'],
      series_names: ['Cumulative Spend'],
      series_data: [
        [120, 280, 520, 780, 950, 1150, 1320],
      ],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
    },
  },
  {
    id: 'bar-grouped',
    name: 'Grouped Bar (Multi-Series)',
    description: '4-series grouped bar across 6 categories.',
    category: 'bar',
    type: 'bar',
    defaultConfig: {
      title: { text: 'Regional Sales by Quarter', subtext: '4 regions × 6 quarters (10K USD)' },
      legend: true,
      theme: 'default',
      type: 'bar',
      categories: ['Q1 22', 'Q2 22', 'Q3 22', 'Q4 22', 'Q1 23', 'Q2 23'],
      series_names: ['North', 'South', 'East', 'West'],
      series_data: [
        [220, 245, 260, 290, 310, 340],
        [180, 200, 215, 240, 255, 280],
        [150, 170, 185, 200, 225, 245],
        [210, 235, 250, 275, 295, 320],
      ],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
    },
  },

  // ---------- Line (extras) ----------
  {
    id: 'line-stack',
    name: 'Stacked Line',
    description: 'Stacked multi-series line — totals plus composition.',
    category: 'line',
    type: 'line',
    defaultConfig: {
      title: { text: 'Monthly Revenue Stack', subtext: 'By product line (10K USD)' },
      legend: true,
      theme: 'default',
      type: 'line',
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
      series_names: ['Basic', 'Pro', 'Enterprise'],
      series_data: [
        [80, 95, 100, 110, 115, 125, 130, 140],
        [60, 70, 80, 85, 90, 100, 110, 115],
        [40, 55, 60, 70, 75, 85, 95, 105],
      ],
      stack: true,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
    },
  },
  {
    id: 'line-step',
    name: 'Step Line',
    description: 'Stepwise line — inventory count at end of each day.',
    category: 'line',
    type: 'line',
    defaultConfig: {
      title: { text: 'Warehouse Inventory', subtext: 'End-of-day stock count' },
      legend: false,
      theme: 'default',
      type: 'line',
      categories: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      series_names: ['Units'],
      // Step-like data — same value held across consecutive days
      series_data: [[500, 500, 480, 480, 480, 350, 350]],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
    },
  },
  {
    id: 'line-multi',
    name: 'Multi-Series Line (5 series)',
    description: '5-series monthly line — compare 5 metrics over a year.',
    category: 'line',
    type: 'line',
    defaultConfig: {
      title: { text: '5-Channel Traffic', subtext: 'Monthly visits by channel' },
      legend: true,
      theme: 'default',
      type: 'line',
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      series_names: ['Search', 'Direct', 'Social', 'Email', 'Ads'],
      series_data: [
        [4200, 4100, 4800, 5200, 5500, 5800, 6100, 6300, 5900, 5400, 5100, 5600],
        [2800, 2700, 3100, 3300, 3500, 3700, 3900, 4100, 3800, 3500, 3300, 3600],
        [1800, 2000, 2400, 2900, 3400, 3900, 4200, 4000, 3500, 2900, 2400, 2100],
        [900, 950, 1100, 1250, 1300, 1400, 1500, 1550, 1450, 1300, 1200, 1300],
        [600, 750, 900, 1100, 1300, 1500, 1700, 1800, 1600, 1400, 1100, 900],
      ],
      stack: false,
      smooth: true,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
    },
  },
  {
    id: 'line-area-stack',
    name: 'Stacked Area',
    description: 'Smooth stacked area — composition + cumulative trend.',
    category: 'line',
    type: 'line',
    defaultConfig: {
      title: { text: 'Daily Signups by Source', subtext: 'Stacked area (smooth)' },
      legend: true,
      theme: 'default',
      type: 'line',
      categories: ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10'],
      series_names: ['Web', 'iOS', 'Android'],
      series_data: [
        [120, 145, 160, 180, 175, 190, 210, 225, 240, 260],
        [85, 95, 110, 125, 130, 145, 160, 175, 185, 200],
        [70, 85, 100, 115, 120, 135, 150, 165, 175, 190],
      ],
      stack: true,
      smooth: true,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
    },
  },
  {
    id: 'line-dual-y',
    name: 'Dual-Metric Line',
    description: 'Two metrics on a shared timeline (temperature & rainfall).',
    category: 'line',
    type: 'line',
    defaultConfig: {
      title: { text: 'Weather vs Rainfall', subtext: 'Avg temperature (°C) and rainfall (mm)' },
      legend: true,
      theme: 'default',
      type: 'line',
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      series_names: ['Temperature (°C)', 'Rainfall (mm)'],
      series_data: [
        [3, 5, 10, 16, 22, 27, 30, 29, 24, 17, 10, 5],
        [25, 30, 45, 60, 85, 130, 175, 160, 95, 60, 40, 28],
      ],
      stack: false,
      smooth: true,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
    },
  },

  // ---------- Pie (extras) ----------
  {
    id: 'pie-rose',
    name: 'Rose Chart',
    description: 'Pie with varying radius per slice — area encodes magnitude.',
    category: 'pie',
    type: 'pie',
    defaultConfig: {
      title: { text: 'Top Programming Languages', subtext: 'By developer mentions (rose)' },
      legend: true,
      theme: 'default',
      type: 'pie',
      categories: [],
      series_names: ['Languages'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      single_series_data: [
        { name: 'JavaScript', value: 9800 },
        { name: 'Python', value: 8600 },
        { name: 'Java', value: 6400 },
        { name: 'TypeScript', value: 5800 },
        { name: 'C#', value: 4200 },
        { name: 'Go', value: 3100 },
        { name: 'Rust', value: 2400 },
        { name: 'Swift', value: 1900 },
      ],
    },
  },
  {
    id: 'pie-nested',
    name: 'Nested Donut',
    description: 'Donut chart with multiple inner rings for hierarchy.',
    category: 'pie',
    type: 'pie',
    defaultConfig: {
      title: { text: 'Revenue Composition', subtext: 'Outer: region · Inner: product' },
      legend: true,
      theme: 'default',
      type: 'pie',
      categories: [],
      series_names: ['Revenue'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      single_series_data: [
        { name: 'Subscription', value: 4200 },
        { name: 'One-time License', value: 2800 },
        { name: 'Professional Services', value: 1700 },
        { name: 'Training', value: 900 },
        { name: 'Other', value: 400 },
      ],
    },
  },
  {
    id: 'pie-half',
    name: 'Half Pie',
    description: 'Half-circle pie — share of recurring vs new customers.',
    category: 'pie',
    type: 'pie',
    defaultConfig: {
      title: { text: 'Customer Mix', subtext: 'Recurring vs New (this quarter)' },
      legend: true,
      theme: 'default',
      type: 'pie',
      categories: [],
      series_names: ['Customers'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      single_series_data: [
        { name: 'Recurring', value: 6850 },
        { name: 'New', value: 2150 },
        { name: 'Reactivated', value: 980 },
        { name: 'Trial-to-Paid', value: 620 },
      ],
    },
  },

  // ---------- Scatter (extras) ----------
  {
    id: 'scatter-bubble',
    name: 'Bubble Scatter',
    description: 'Scatter plot with widely varied magnitudes — bubble-like.',
    category: 'scatter',
    type: 'scatter',
    defaultConfig: {
      title: { text: 'Marketing Spend vs Revenue', subtext: 'Per campaign' },
      legend: true,
      theme: 'default',
      type: 'scatter',
      categories: [],
      series_names: ['Campaigns'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
      scatter_data: [
        [50, 320], [80, 510], [120, 780], [200, 1450], [35, 210],
        [150, 1100], [95, 690], [180, 1380], [240, 1820], [70, 480],
        [110, 820], [165, 1240], [220, 1680], [60, 410], [135, 990],
        [85, 620], [195, 1500], [175, 1320], [230, 1750], [105, 760],
      ],
    },
  },
  {
    id: 'scatter-matrix',
    name: 'Clustered Scatter',
    description: 'Scatter showing two visually distinct data clusters.',
    category: 'scatter',
    type: 'scatter',
    defaultConfig: {
      title: { text: 'Customer Segments', subtext: 'Two clusters: high-value vs mass-market' },
      legend: true,
      theme: 'default',
      type: 'scatter',
      categories: [],
      series_names: ['Customers'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
      scatter_data: [
        // Cluster A — high-value, low frequency
        [12, 880], [15, 920], [18, 1100], [22, 1250], [25, 1320],
        [14, 860], [19, 1080], [21, 1180], [23, 1280], [17, 990],
        // Cluster B — mass market, high frequency, lower value
        [85, 220], [92, 240], [78, 195], [88, 215], [95, 255],
        [82, 205], [90, 235], [86, 218], [98, 260], [80, 200],
      ],
    },
  },

  // ---------- Radar (extras) ----------
  {
    id: 'radar-multi',
    name: 'Multi-Series Radar',
    description: '3-series radar — compare three products across 6 dimensions.',
    category: 'radar',
    type: 'radar',
    defaultConfig: {
      title: { text: 'Product Capability Comparison', subtext: '3 products × 6 dimensions' },
      legend: true,
      theme: 'default',
      type: 'radar',
      categories: [],
      series_names: ['Product A', 'Product B', 'Product C'],
      series_data: [
        [88, 75, 92, 80, 70, 85],
        [72, 90, 65, 85, 88, 75],
        [80, 70, 78, 75, 92, 90],
      ],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      radar_indicators: [
        { name: 'Features', max: 100 },
        { name: 'Usability', max: 100 },
        { name: 'Performance', max: 100 },
        { name: 'Reliability', max: 100 },
        { name: 'Support', max: 100 },
        { name: 'Price', max: 100 },
      ],
    },
  },

  // ---------- Funnel (extras) ----------
  {
    id: 'funnel-side',
    name: 'Onboarding Funnel',
    description: 'Funnel with several steps — drop-off between onboarding stages.',
    category: 'funnel',
    type: 'funnel',
    defaultConfig: {
      title: { text: 'Onboarding Drop-off', subtext: 'From install to activated' },
      legend: true,
      theme: 'default',
      type: 'funnel',
      categories: [],
      series_names: ['Onboarding'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      single_series_data: [
        { name: 'App Install', value: 25000 },
        { name: 'Sign Up', value: 18200 },
        { name: 'Complete Profile', value: 12100 },
        { name: 'First Action', value: 8400 },
        { name: 'Return Day 2', value: 5300 },
        { name: 'Activated', value: 3100 },
      ],
    },
  },

  // ---------- Gauge (extras) ----------
  {
    id: 'gauge-half',
    name: 'Half-Circle Gauge',
    description: 'Single-value gauge — server CPU load.',
    category: 'gauge',
    type: 'gauge',
    defaultConfig: {
      title: { text: 'Server CPU Load', subtext: 'Current usage (%)' },
      legend: false,
      theme: 'default',
      type: 'gauge',
      categories: [],
      series_names: ['CPU'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      gauge_value: 73,
      gauge_max: 100,
    },
  },
  {
    id: 'gauge-multi',
    name: 'Score Gauge (0-10)',
    description: 'Gauge with non-100 max — credit score on a 0-10 scale.',
    category: 'gauge',
    type: 'gauge',
    defaultConfig: {
      title: { text: 'Credit Score', subtext: 'Applicant risk rating (0-10)' },
      legend: false,
      theme: 'default',
      type: 'gauge',
      categories: [],
      series_names: ['Score'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      gauge_value: 7.8,
      gauge_max: 10,
    },
  },

  // ---------- Candlestick (NEW) ----------
  {
    id: 'candlestick',
    name: 'Candlestick (K-Line)',
    description: 'OHLC candlestick — daily price action for a stock.',
    category: 'candlestick',
    type: 'candlestick',
    defaultConfig: {
      title: { text: 'AAPL Daily OHLC', subtext: '10-day candlestick (USD)' },
      legend: false,
      theme: 'default',
      type: 'candlestick',
      categories: [
        'Jun 03', 'Jun 04', 'Jun 05', 'Jun 06', 'Jun 07',
        'Jun 10', 'Jun 11', 'Jun 12', 'Jun 13', 'Jun 14',
      ],
      series_names: ['AAPL'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
      candlestick_data: [
        [180.5, 183.2, 179.8, 184.0],
        [183.0, 182.5, 181.0, 184.5],
        [182.5, 186.8, 182.2, 187.2],
        [186.8, 185.5, 184.8, 187.5],
        [185.5, 188.0, 185.0, 188.5],
        [188.0, 190.2, 187.5, 191.0],
        [190.2, 189.5, 188.0, 191.2],
        [189.5, 192.8, 189.0, 193.5],
        [192.8, 194.5, 192.0, 195.2],
        [194.5, 193.0, 191.8, 195.0],
      ],
    },
  },

  // ---------- Boxplot (NEW) ----------
  {
    id: 'boxplot',
    name: 'Box Plot',
    description: 'Distribution per category — min / Q1 / median / Q3 / max.',
    category: 'boxplot',
    type: 'boxplot',
    defaultConfig: {
      title: { text: 'Exam Scores by Class', subtext: '5-number summary per class' },
      legend: false,
      theme: 'default',
      type: 'boxplot',
      categories: ['Class A', 'Class B', 'Class C', 'Class D', 'Class E'],
      series_names: ['Scores'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
      boxplot_data: [
        [45, 62, 75, 84, 98],
        [50, 68, 78, 88, 95],
        [40, 55, 70, 80, 92],
        [55, 72, 82, 90, 100],
        [48, 65, 73, 85, 94],
      ],
    },
  },

  // ---------- Graph (NEW) ----------
  {
    id: 'graph',
    name: 'Relationship Graph',
    description: 'Force-directed graph — nodes & edges between entities.',
    category: 'graph',
    type: 'graph',
    defaultConfig: {
      title: { text: 'Social Network', subtext: 'Friends & colleagues (force layout)' },
      legend: true,
      theme: 'default',
      type: 'graph',
      categories: [],
      series_names: [],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      graph_nodes: [
        { id: '1', name: 'Alice', category: 0 },
        { id: '2', name: 'Bob', category: 0 },
        { id: '3', name: 'Carol', category: 0 },
        { id: '4', name: 'Dave', category: 1 },
        { id: '5', name: 'Eve', category: 1 },
        { id: '6', name: 'Frank', category: 1 },
        { id: '7', name: 'Grace', category: 2 },
        { id: '8', name: 'Heidi', category: 2 },
        { id: '9', name: 'Ivan', category: 2 },
      ],
      graph_links: [
        { source: '1', target: '2' },
        { source: '1', target: '3' },
        { source: '2', target: '3' },
        { source: '1', target: '4' },
        { source: '4', target: '5' },
        { source: '5', target: '6' },
        { source: '4', target: '6' },
        { source: '3', target: '7' },
        { source: '7', target: '8' },
        { source: '8', target: '9' },
        { source: '7', target: '9' },
        { source: '2', target: '5' },
        { source: '6', target: '8' },
      ],
    },
  },

  // ---------- Sankey (NEW) ----------
  {
    id: 'sankey',
    name: 'Sankey Diagram',
    description: 'Flow composition — energy / cost / user-flow Sankey.',
    category: 'sankey',
    type: 'sankey',
    defaultConfig: {
      title: { text: 'User Flow Sankey', subtext: 'From landing page to purchase' },
      legend: false,
      theme: 'default',
      type: 'sankey',
      categories: [],
      series_names: [],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      sankey_nodes: [
        { name: 'Homepage' },
        { name: 'Product Page' },
        { name: 'Pricing' },
        { name: 'Cart' },
        { name: 'Checkout' },
        { name: 'Purchase' },
        { name: 'Bounce' },
      ],
      sankey_links: [
        { source: 'Homepage', target: 'Product Page', value: 5400 },
        { source: 'Homepage', target: 'Pricing', value: 2100 },
        { source: 'Homepage', target: 'Bounce', value: 3200 },
        { source: 'Product Page', target: 'Cart', value: 2800 },
        { source: 'Product Page', target: 'Bounce', value: 2600 },
        { source: 'Pricing', target: 'Cart', value: 1200 },
        { source: 'Pricing', target: 'Bounce', value: 900 },
        { source: 'Cart', target: 'Checkout', value: 3200 },
        { source: 'Cart', target: 'Bounce', value: 800 },
        { source: 'Checkout', target: 'Purchase', value: 2400 },
        { source: 'Checkout', target: 'Bounce', value: 800 },
      ],
    },
  },

  // ---------- Treemap (NEW) ----------
  {
    id: 'treemap',
    name: 'Treemap',
    description: 'Hierarchical rectangles — area encodes share of total.',
    category: 'treemap',
    type: 'treemap',
    defaultConfig: {
      title: { text: 'Cloud Spend by Service', subtext: 'Share of monthly budget' },
      legend: false,
      theme: 'default',
      type: 'treemap',
      categories: [],
      series_names: ['Spend'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      single_series_data: [
        { name: 'Compute (EC2)', value: 8500 },
        { name: 'Storage (S3)', value: 3200 },
        { name: 'Database (RDS)', value: 4100 },
        { name: 'Networking', value: 1800 },
        { name: 'CDN', value: 2400 },
        { name: 'Serverless (Lambda)', value: 1500 },
        { name: 'AI / ML', value: 2800 },
        { name: 'Other', value: 1200 },
      ],
    },
  },

  // ---------- Sunburst (NEW) ----------
  {
    id: 'sunburst',
    name: 'Sunburst',
    description: 'Radial hierarchy — nested rings from root to leaves.',
    category: 'sunburst',
    type: 'sunburst',
    defaultConfig: {
      title: { text: 'Org Headcount', subtext: 'Sunburst by department → team' },
      legend: false,
      theme: 'default',
      type: 'sunburst',
      categories: [],
      series_names: ['Headcount'],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: true,
      showToolbox: true,
      sunburst_data: [
        {
          name: 'Engineering',
          children: [
            { name: 'Frontend', value: 28 },
            { name: 'Backend', value: 35 },
            { name: 'Mobile', value: 14 },
            { name: 'DevOps', value: 10 },
          ],
        },
        {
          name: 'Product',
          children: [
            { name: 'PM', value: 12 },
            { name: 'Design', value: 16 },
            { name: 'Research', value: 6 },
          ],
        },
        {
          name: 'Go-to-Market',
          children: [
            { name: 'Sales', value: 32 },
            { name: 'Marketing', value: 18 },
            { name: 'Customer Success', value: 22 },
          ],
        },
        {
          name: 'Operations',
          children: [
            { name: 'HR', value: 8 },
            { name: 'Finance', value: 7 },
            { name: 'Legal', value: 4 },
          ],
        },
      ],
    },
  },

  // ---------- Parallel (NEW) ----------
  {
    id: 'parallel',
    name: 'Parallel Coordinates',
    description: 'Multi-dimensional data — one polyline per record.',
    category: 'parallel',
    type: 'parallel',
    defaultConfig: {
      title: { text: 'Car Specs Parallel', subtext: 'MPG / cylinders / HP / weight / acceleration' },
      legend: false,
      theme: 'default',
      type: 'parallel',
      categories: [],
      series_names: [],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
      parallel_dims: ['MPG', 'Cylinders', 'Horsepower', 'Weight', '0-60 (s)'],
      parallel_data: [
        [18, 8, 130, 3504, 12],
        [15, 8, 165, 3693, 11.5],
        [18, 8, 150, 3436, 11],
        [16, 8, 140, 3433, 10.5],
        [17, 8, 130, 3449, 10.5],
        [21, 6, 110, 3907, 13],
        [24, 4, 95, 2372, 15],
        [22, 6, 95, 2582, 14.5],
        [30, 4, 75, 2155, 16.5],
        [32, 4, 71, 2204, 19],
      ],
    },
  },

  // ---------- ThemeRiver (NEW) ----------
  {
    id: 'themeRiver',
    name: 'Theme River',
    description: 'Time-series river — multiple categories flowing over time.',
    category: 'themeRiver',
    type: 'themeRiver',
    defaultConfig: {
      title: { text: 'Topic Mentions River', subtext: 'Weekly mention volume by topic' },
      legend: true,
      theme: 'default',
      type: 'themeRiver',
      categories: [],
      series_names: [],
      series_data: [],
      stack: false,
      smooth: false,
      horizontal: false,
      showLabel: false,
      showToolbox: true,
      themeriver_data: [
        ['2024-01-01', 120, 'AI'],
        ['2024-01-08', 180, 'AI'],
        ['2024-01-15', 240, 'AI'],
        ['2024-01-22', 320, 'AI'],
        ['2024-01-29', 410, 'AI'],
        ['2024-01-01', 80, 'Cloud'],
        ['2024-01-08', 95, 'Cloud'],
        ['2024-01-15', 110, 'Cloud'],
        ['2024-01-22', 130, 'Cloud'],
        ['2024-01-29', 145, 'Cloud'],
        ['2024-01-01', 60, 'Mobile'],
        ['2024-01-08', 75, 'Mobile'],
        ['2024-01-15', 70, 'Mobile'],
        ['2024-01-22', 85, 'Mobile'],
        ['2024-01-29', 95, 'Mobile'],
        ['2024-01-01', 40, 'Web3'],
        ['2024-01-08', 55, 'Web3'],
        ['2024-01-15', 50, 'Web3'],
        ['2024-01-22', 45, 'Web3'],
        ['2024-01-29', 35, 'Web3'],
      ],
    },
  },
]

/** Quick lookup by template id. */
export const TEMPLATE_BY_ID: Record<string, EChartsTemplate> = ECHARTS_TEMPLATES.reduce(
  (acc, t) => {
    acc[t.id] = t
    return acc
  },
  {} as Record<string, EChartsTemplate>,
)

/** Default template used when the editor is mounted with no config. */
export const DEFAULT_TEMPLATE = ECHARTS_TEMPLATES[0]

export const THEME_OPTIONS: { value: string; label: string }[] = [
  { value: 'default', label: 'Default' },
  { value: 'dark', label: 'Dark' },
  { value: 'vintage', label: 'Vintage' },
  { value: 'macarons', label: 'Macarons' },
]
